beck_jonathan_file_upload:
    pattern:  /admin/file-upload/{fileFolder}/{fileName}/{maxFiles}
    defaults: { _controller: BeckJonathanFileBundle:File:upload, fileFolder: null, fileName: null, maxFiles: null }